#!/bin/sh

# check if add-delete.test.dyndns exists. It should not.
cleandig add-delete.test.dyndns ANY hidesoadetails

# add a record
nsupdate <<! | sed 's/\, id:.*/ ID_REPLACED/'
server $nameserver $port
zone test.dyndns
prereq nxrrset add-delete.test.dyndns A
update add add-delete.test.dyndns. 3600 A 127.0.0.108
send
answer
!

# query if the record now exists
cleandig add-delete.test.dyndns ANY

# delete the just added record
nsupdate <<! | sed 's/\, id:.*/ ID_REPLACED/'
server $nameserver $port
zone test.dyndns
prereq yxrrset add-delete.test.dyndns A
update delete add-delete.test.dyndns.
send
answer
!

# check if the record was deleted.
cleandig add-delete.test.dyndns ANY hidesoadetails
