.TH DNSSCOPE 8 "September 2012" "PowerDNS"
.SH NAME
dnsscope \- A PowerDNS nameserver debugging tool
.SH SYNOPSIS
.B dnsscope  \fI[infile]\fR
.SH DESCRIPTION
dnsscope takes an \fIinfile\fR in PCAP format. It generates some simple statistics outputs these to STDOUT.
.SH OPTIONS
None.
.SH SEE ALSO
pcap(3PCAP), tcpdump(8)
.SH AUTHORS
This manpage was written by Joerg Jungermann (jj+debian At borkum.net) for the
Debian Project and the PowerDNS versatile DNS server.
