#!/bin/sh
sed \
's|\<c\([0-9][0-9][0-9]*\)\>|<ulink url="http://wiki.powerdns.com/projects/trac/changeset/\1">commit \1</ulink>|g' |
sed \
's|\<C\([0-9][0-9][0-9]*\)\>|<ulink url="http://wiki.powerdns.com/projects/trac/changeset/\1">\1</ulink>|g' |
sed \
's|\<g\([0-9a-f]\{7\}\)\>|<ulink url="https://github.com/PowerDNS/pdns/commit/\1">commit \1</ulink>|g' |
sed \
's|\<G\([0-9a-f]\{7\}\)\>|<ulink url="https://github.com/PowerDNS/pdns/commit/\1">\1</ulink>|g' |
sed \
's|\<T\([0-9][0-9]*\)\>| <ulink url="https://github.com/PowerDNS/pdns/issues/\1">\1</ulink>|g' |
sed \
's|\<t\([0-9][0-9]+\)\>| <ulink url="https://github.com/PowerDNS/pdns/issues/\1">ticket \1</ulink>|g' 
