#!/bin/sh
#
#

set -e

case "$1" in
  configure)
    if [ -z "`getent group pdns`" ]; then
      addgroup --quiet --system pdns
    fi
    if [ -z "`getent passwd pdns`" ]; then
      echo -n "Creating user and group pdns..."
      adduser --quiet --system --home /var/spool/powerdns --shell /bin/false --ingroup pdns --disabled-password --disabled-login --gecos "PowerDNS" pdns
      echo "done"
    fi
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

# Those using dependency based boot sequencing with sysv-rc and
# installing pdns-recursor version 3.1.7.1-2 or earlier would have wrong
# runlevel symlinks.  Recover from this.
if [ "$1" = "configure" ] && dpkg --compare-versions "$2" le "3.1.7.1-2" \
	&& [ -f /etc/rc2.d/S[0-9][0-9]pdns-recursor ] && [ ! -f /etc/rc1.d/K[0-9][0-9]pdns-recursor ]
then
	update-rc.d -f pdns-recursor remove
fi

# Init script has errors in previous versions. Postinst script should just
# return the exit status of this script
initscript_error() {
	return $1
}

#DEBHELPER#

exit 0

