#!/bin/sh
cleandig google-alias.example.com A hidettl
cleandig google-alias.example.com AAAA hidettl
cleandig google-alias.example.com A hidettl tcp
cleandig google-alias.example.com AAAA hidettl tcp
# Commented out as it causes TC set in answer in the *-both tests
#cleandig google-alias.example.com ANY hidettl
cleandig google-alias.example.com ANY hidettl tcp

# Test if the NSEC bitmap is correct
cleandig google-alias1.example.com A hidettl hidesoadetails dnssec
