# USAGE

#   docker build --build-arg MAKEFLAGS=-j8 -t recursor -f Dockerfile-recursor .
#   docker run -p 1053:53 -p 1053:53/udp -ti --rm recursor
#   dig a www.example.com @0 -p 1053

FROM debian:trixie-slim AS builder
ENV DEBIAN_FRONTEND=noninteractive

# Reusable layer for base update
RUN apt-get update && \
    apt-get dist-upgrade -y && \
    apt-get clean

# devscripts provides mk-build-deps and more
RUN apt-get install -y --no-install-recommends \
        devscripts \
        equivs \
        git \
        cmake \
        curl \
        jq \
        libclang-dev \
        meson \
        ninja-build

# TODO: make sure /source looks roughly the same from git or tar
WORKDIR /source

# import everything (could be pdns.git or a tarball)
COPY builder-support/ builder-support/

# TODO: control file is not in tarballs at all right now
RUN mk-build-deps -i -t 'apt-get -o Debug::pkgProblemResolver=yes -y --no-install-recommends' builder-support/debian/recursor/debian-buster/control && \
    apt-get clean

# Install Rust
COPY builder-support/helpers/install_rust.sh install_rust.sh
COPY builder-support/helpers/rust.json rust.json
RUN ./builder-support/helpers/install_rust.sh

WORKDIR /source
COPY meson/ meson/
COPY pdns/ pdns/
COPY ext/ ext/
COPY .git/ .git/

# build and install (TODO: before we hit this line, rearrange /source structure if we are coming from a tarball)
WORKDIR /source/pdns/recursordist

# avoid installing pandoc
RUN touch pdns_recursor.1 rec_control.1

# Install Lua
ARG NO_LUA_JIT="s390x"
RUN LUAVER=$([ -z "${NO_LUA_JIT##*$(dpkg --print-architecture)*}" ] && echo 'lua5.3' || echo 'luajit') && \
    apt-get install -y --no-install-recommends lib${LUAVER}-*dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ARG DOCKER_FAKE_RELEASE="NO"
ARG MAKEFLAGS="-j2"
RUN mkdir /build && \
    BUILDDIR=$(mktemp -d) && \
    IS_RELEASE="${DOCKER_FAKE_RELEASE}" \
    LDFLAGS="-latomic -fuse-ld=lld -Wl,--build-id=sha1 -ldl" \
    CC=clang \
    CXX=clang++ \
    PKG_CONFIG_PATH=/opt/lib/pkgconfig meson setup ${BUILDDIR} \
      --sysconfdir=/etc/powerdns \
      -Db_lto=true \
      -Db_lto_mode=thin \
      -Db_pie=true \
      -Dlibcap=enabled \
      -Dsigners-libsodium=enabled \
      -Dlua=auto \
      -Dsnmp=enabled \
      -Ddns-over-tls=enabled \
      -Ddnstap=enabled \
      -Dnod=enabled \
      -Dsystemd-service=disabled && \
    meson compile -C ${BUILDDIR} && \
    meson install -C ${BUILDDIR} --destdir /build && \
    strip /build/usr/local/bin/* && \
    # remove systemd unit files, we do not need them and copying /lib to the run-time image breaks it
    rm -rf /build/lib

WORKDIR /tmp
RUN mkdir debian && \
    echo 'Source: docker-deps-for-pdns' > debian/control && \
    dpkg-shlibdeps /build/usr/local/bin/rec_control /build/usr/local/sbin/pdns_recursor && \
    sed 's/^shlibs:Depends=/Depends: /' debian/substvars >> debian/control && \
    equivs-build debian/control && \
    mkdir /build/tmp/ && \
    dpkg-deb -I equivs-dummy_1.0_all.deb && cp equivs-dummy_1.0_all.deb /build/tmp/


# Runtime
FROM debian:trixie-slim

# Reusable layer for base update
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y && \
    apt-get clean

# Copy build output
COPY --from=builder /build /

# FIXME: better not use /build/tmp for equivs at all
RUN chmod 1777 /tmp

# Install dependencies
# - python3 + jinja2 (for startup script)
# - tini (for signal management)
# - adduser (for adding an unprivileged user)
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
        python3 python3-jinja2 \
        tini \
        adduser libcap2-bin \
        /tmp/equivs-dummy_1.0_all.deb && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Create unprivileged pdns user and directories
RUN adduser --system --disabled-password --disabled-login --no-create-home --group pdns --uid 953 && \
    install -d --owner pdns --group pdns /var/run/pdns-recursor /etc/powerdns/recursor.d /etc/powerdns/templates.d

COPY dockerdata/startup.py /usr/local/sbin/pdns_recursor-startup
COPY dockerdata/recursor.conf /etc/powerdns/

# Default DNS ports
EXPOSE 53/udp
EXPOSE 53/tcp

# Default webserver port
EXPOSE 8082/tcp

USER pdns
ENTRYPOINT ["/usr/bin/tini", "--", "/usr/local/sbin/pdns_recursor-startup"]
HEALTHCHECK --interval=10s --timeout=5s --start-period=1s --start-interval=1s --retries=3 CMD ["rec_control", "pingsilent"]
