#!/usr/bin/env bash

cleannsupdate <<!
server $nameserver $port
zone test.dyndns
update delete test.dyndns SOA ns1.test.dyndns. ahu.example.dyndns. 2050101001 28800 7200 604800 86400
update add test.dyndns. 3600 SOA ns1.test.dyndns. ahu.example.dyndns. 4197584648 28800 7200 604800 86400
send
answer
!
cleannsupdate <<!
server $nameserver $port
zone test.dyndns
update delete test.dyndns SOA ns1.test.dyndns. ahu.example.dyndns. 4197584648 28800 7200 604800 86400
update add test.dyndns. 3600 SOA ns1.test.dyndns. ahu.example.dyndns. 2012060701 28800 7200 604800 86400
send
answer
!


cleandig test.dyndns SOA


cleannsupdate <<!
server $nameserver $port
zone sub.test.dyndns
update delete sub.test.dyndns SOA ns1.test.dyndns. ahu.example.dyndns. 2050101001 28800 7200 604800 86400
update add sub.test.dyndns. 3600 SOA ns1.test.dyndns. ahu.example.dyndns. 4197584648 28800 7200 604800 86400
send
answer
!
cleannsupdate <<!
server $nameserver $port
zone test.dyndns
update delete test.dyndns SOA ns1.test.dyndns. ahu.example.dyndns. 4197584648 28800 7200 604800 86400
update add test.dyndns. 3600 SOA ns1.test.dyndns. ahu.example.dyndns. 2012060701 28800 7200 604800 86400
send
answer
!


cleandig test.dyndns SOA
