#!/usr/bin/env bash

for zone in test.dyndns sub.test.dyndns
do
    $PDNSUTIL --config-dir=. --config-name=$backend \
        replace-rrset ${zone} @ SOA "ns1.test.dyndns ahu.example.dyndns 2012060701 28800 7200 604800 86400" \
        > /dev/null
done
