#!/bin/bash

TIMERANGE=$(drill -D @127.0.0.1 -p 5300 powerdnssec.org -t soa | grep RRSIG | head -1 | 
	awk '{printf "-e %s -i %s", $9, $10}')

PLAINZONE=$1
ZSKID=$(drill -D @127.0.0.1 -p 5300 powerdnssec.org -t soa  | grep RRSIG | cut -f2 -d{ | cut -f1 -d} | awk '{print $3}')
ZSKFNAME=$(echo /home/ahu/work/pdns/pdns/pdns/keys/$1/keys/000002*zsk.active.private | sed s/.private//)

ldns-signzone $2 $3 $4 $1 $TIMERANGE $ZSKFNAME
echo Zone signed with key id $ZSKID now in $1.signed