# Minimal makefile for Sphinx documentation
#

# You can set these variables from the command line.
SPHINXOPTS    =
SPHINXBUILD   = .venv/bin/sphinx-build
SPHINXPROJ    = PowerDNSRecursor
SOURCEDIR     = .
BUILDDIR      = _build

# Put it first so that "make" without argument is like "make help".
help: .venv
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

.PHONY: help Makefile.sphinx generate-jsonschema.py http-api/authoritative-api-swagger.yaml

http-api/recursor-generated-schema.yaml: .venv generate-jsonschema.py http-api/authoritative-api-swagger.yaml
	.venv/bin/python ./generate-jsonschema.py http-api/authoritative-api-swagger.yaml $@ 

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile.sphinx .venv http-api/recursor-generated-schema.yaml
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

.venv:
	python3 -m venv .venv
	.venv/bin/pip install -U pip setuptools
	.venv/bin/pip install -r requirements.txt


