[package]
name = "settings"
version = "0.1.0"
edition = "2021"

[lib]
name = "settings"
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
ipnet = "2.8"
once_cell = "1.18.0"

[build-dependencies]
cxx-build = "1.0"

