usr/bin/pdns_control
usr/bin/zone2json
usr/bin/zone2sql
usr/bin/pdnsutil
usr/lib/*/pdns/libbindbackend.so*
usr/lib/*/pdns/librandombackend.so*
usr/sbin/pdns_server
debian/config/pdns.local.conf usr/share/pdns-server/
debian/config/pdns usr/share/pdns-server/
debian/config/pdns.simplebind.conf usr/share/pdns-server/
debian/resolvconf/pdns etc/resolvconf/update.d/
debian/insserv.d/pdns-server etc/insserv.d/
lib/systemd/system/pdns.service
lib/systemd/system/pdns@.service
