// !! This file has been generated by dnsdist-rules-generator.py, do not edit by hand!!
luaCtx.writeFunction("AllowResponseAction", []() {
  return dnsdist::actions::getAllowResponseAction();
});
luaCtx.writeFunction("DelayResponseAction", [](uint32_t msec) {
  return dnsdist::actions::getDelayResponseAction(msec);
});
luaCtx.writeFunction("DropResponseAction", []() {
  return dnsdist::actions::getDropResponseAction();
});
luaCtx.writeFunction("LogResponseAction", [](boost::optional<std::string> file_name, boost::optional<bool> append, boost::optional<bool> buffered, boost::optional<bool> verbose_only, boost::optional<bool> include_timestamp) {
  return dnsdist::actions::getLogResponseAction(file_name ? *file_name : "", append ? *append : false, buffered ? *buffered : false, verbose_only ? *verbose_only : true, include_timestamp ? *include_timestamp : false);
});
luaCtx.writeFunction("LuaFFIPerThreadResponseAction", [](std::string code) {
  return dnsdist::actions::getLuaFFIPerThreadResponseAction(code);
});
luaCtx.writeFunction("SetEDNSOptionResponseAction", [](uint32_t code, std::string data) {
  return dnsdist::actions::getSetEDNSOptionResponseAction(code, data);
});
luaCtx.writeFunction("SetExtendedDNSErrorResponseAction", [](uint16_t info_code, boost::optional<std::string> extra_text) {
  return dnsdist::actions::getSetExtendedDNSErrorResponseAction(info_code, extra_text ? *extra_text : "");
});
luaCtx.writeFunction("SetReducedTTLResponseAction", [](uint8_t percentage) {
  return dnsdist::actions::getSetReducedTTLResponseAction(percentage);
});
luaCtx.writeFunction("SetSkipCacheResponseAction", []() {
  return dnsdist::actions::getSetSkipCacheResponseAction();
});
luaCtx.writeFunction("SetTagResponseAction", [](std::string tag, std::string value) {
  return dnsdist::actions::getSetTagResponseAction(tag, value);
});
luaCtx.writeFunction("SNMPTrapResponseAction", [](boost::optional<std::string> reason) {
  return dnsdist::actions::getSNMPTrapResponseAction(reason ? *reason : "");
});
luaCtx.writeFunction("TCResponseAction", []() {
  return dnsdist::actions::getTCResponseAction();
});
