#!/bin/sh
../pdns/sdig $nameserver $port $1 $2 $3 | sort
drill -a -p $port -o rd -D -S -k trustedkeys $1 $2 @$nameserver > $testname/drillchase.out 2>&1 
echo $? >> $testname/drillchase.out
drill -a -p $port -o rd -D -k trustedkeys $1 $2 @$nameserver > $testname/drill.out 2>&1
echo $? >> $testname/drill.out
/usr/lib/go/bin/q -rd=false -check -dnssec -port=$port @$nameserver $2 $1 > $testname/q.out 2>&1
echo $? >> $testname/q.out
if [ ! -e $testname/skip-unboundhost ]
then
	unbound-host -v -C unbound-host.conf -t $2 $1 > $testname/unbound-host.out 2>&1
	echo $? >> $testname/unbound-host.out
fi