#!/bin/bash
PATH=.:$PATH

rm -f test-results failed_tests passed_tests

passed=0
failed=0

for a in $(find . -type d | grep -v ^.$ | sed s:^./:: | grep -v .svn) 
do
	echo  "$a: "
	cat $a/description 

	echo  "$a: " >> test-results
	cat $a/description >> test-results
	
	$a/command > /dev/null
	$a/command > $a/real_result
	diff -u $a/expected_result $a/real_result > $a/diff
	if [ -s $a/diff ] 
	then
		result="	Failed test $a"
		echo $a >> failed_tests
		failed=$[$failed+1]
	else
		result="	Passed test $a"
		echo $a >> passed_tests
		passed=$[$passed+1]
	fi
	
	echo "$result"
	echo
	echo "$result" >> test-results
	echo >> test-results
done

echo -n $passed out of $[$passed+$failed] 
echo -n " ("
res=$((echo scale=2; echo 100*$passed/\($passed+$failed\)) | bc )
echo -n "$res%) "
echo tests passed

