#!/bin/bash
PATH=.:$PATH

make -C ../pdns sdig nsec3dig || exit 1

rm -f test-results failed_tests passed_tests skipped_tests ${testsdir}/*/real_result ${testdir}/*/diff ${testdir}/*/*.out

passed=0
failed=0
skipped=0

touch passed_tests failed_tests skipped_tests

for a in $(find $testsdir -type d | grep -v ^.$ | grep -v .svn | grep -v ^confdir | LC_ALL=C sort) 
do
	if [ ! -x $a/command ]
	then
		continue
	fi
	testname=$(basename $a)
	export testname
	echo  "$testname: "
	cat $a/description 

	echo  "$testname: " >> test-results
	cat $a/description >> test-results
	
	SKIPIT=0
	if [ -e $a/skip ] 
	then
		SKIPIT=1
		result="	Skipped test $a"
	else
		for reason in $skipreasons "$context"
		do
			if [ -e $a/skip.$reason ]
			then
				SKIPIT=1
				result="	Skipped test $a for reason $reason"
				break
			fi
		done
	fi
				
	if [ $SKIPIT = 1 ]
	then
		echo $testname >> skipped_tests
		skipped=$[$skipped+1]
	else	
		$a/command > /dev/null
		$a/command > $a/real_result
		expected=$a/expected_result
		for extracontext in $extracontexts
		do
			[ -e "$a/expected_result.$extracontext" ] && expected=$a/expected_result.$extracontext
		done
		[ -n "$context" ] && [ -e "$a/expected_result.$context" ] && expected=$a/expected_result.$context
		diff -u $expected $a/real_result > $a/diff
		if [ -s $a/diff ] 
		then
			result="	Failed test $a"
			echo $testname >> failed_tests
			failed=$[$failed+1]
		else
			result="	Passed test $a"
			echo $testname >> passed_tests
			passed=$[$passed+1]
		fi
	fi	
	echo "$result"
	echo
	echo "$result" >> test-results
	echo >> test-results
done

echo -n $passed out of $[$passed+$failed]
echo -n " ("
res=$((echo scale=2; echo 100*$passed/\($passed+$failed\)) | bc )
echo -n "$res%) "
echo tests passed, $skipped were skipped
