#!/usr/bin/env bash

if [ ! -d .venv ]; then
	virtualenv .venv
fi
. .venv/bin/activate
python -V
pip install -r requirements.txt

set -e
if [ "${PDNS_DEBUG}" = "YES" ]; then
  set -x
fi
exec ./runtests.py "$@"
