#!/bin/sh
truncate -s 0 configs/10.0.3.24/questions.txt
cleandig hOsT.lOwErcAsE-outgoing.example.net a >/dev/null 2>&1
$SDIG $nameserver 5300 hOsT.lOwErcAsE-outgoing.example.net a recurse >/dev/null 2>&1
cat configs/10.0.3.24/questions.txt
