#!/bin/sh
VERSION="unknown"

if [ ! -z "$(git rev-parse --abbrev-ref HEAD)" ]; then
  if [ $(git rev-parse --abbrev-ref HEAD | grep -q 'rel/') ]; then
    REL_TYPE="$(git rev-parse --abbrev-ref HEAD | cut -d/ -f 2 | cut -d- -f 1)"
    VERSION="$(git describe --match='${REL_TYPE}-*' --dirty=-dirty )"
  else
    GIT_VERSION=$(git show --no-patch --format=format:%h HEAD)
    BRANCH="$(git rev-parse --abbrev-ref HEAD | perl -p -e 's/-//g')"
    if [ "${BRANCH}" = "master" ]; then
      VERSION="0.0.${PDNS_BUILD_NUMBER}g${GIT_VERSION}"
    else
      VERSION="0.0.${BRANCH}.${PDNS_BUILD_NUMBER}g${GIT_VERSION}"
    fi
  fi
  echo "$VERSION" > .version
elif [ -f .version ]; then
  VERSION="$(cat .version)"
fi

echo $VERSION
