.SILENT:

all:

install:

uninstall:

distclean: clean

clean:

check:

distdir:
	mkdir -p $(distdir)/include/rapidjson/internal
	cp license.txt $(distdir)
	cp include/rapidjson/*.h $(distdir)/include/rapidjson
	cp include/rapidjson/internal/*.h $(distdir)/include/rapidjson/internal
