#!/usr/bin/env bash

NOW=$(date +%s)

# lower SOA so that the test makes sense
$PDNSUTIL --config-dir=. --config-name=$backend \
    replace-rrset test.dyndns @ SOA "ns1.test.dyndns ahu.example.dyndns 10 28800 7200 604800 86400" \
    > /dev/null

$PDNSUTIL --config-dir=. --config-name=$backend list-zone test.dyndns | grep SOA

$PDNSUTIL --config-dir=. --config-name=$backend set-meta test.dyndns SOA-EDIT INCEPTION-EPOCH

$PDNSUTIL --config-dir=. --config-name=$backend increase-serial test.dyndns > /dev/null

NEWSERIAL=$($PDNSUTIL --config-dir=. --config-name=$backend list-zone test.dyndns | grep SOA | awk '{print $7}')

NOWPLUSTEN=$((NOW + 10))

if [ $NOW -le $NEWSERIAL ] && [ $NOW -le $NOWPLUSTEN ]
then
	echo New serial is within range
else
	echo New serial is NOT within range
fi

# remove meta
$PDNSUTIL --config-dir=. --config-name=$backend set-meta test.dyndns SOA-EDIT

# restore old SOA
$PDNSUTIL --config-dir=. --config-name=$backend \
    replace-rrset test.dyndns @ SOA "ns1.test.dyndns ahu.example.dyndns 2012060701 28800 7200 604800 86400" \
    > /dev/null
