apiVersion: v1
kind: ConfigMap
metadata:
  name: powerdns-clients-res
  namespace: powerdns-clients-<ENV_ROLE>
data:
  recursor.conf: |
    config-name=recursor-1
    local-address=0.0.0.0
    local-port=5353
    loglevel=6
    version-string=powerdns
    webserver-loglevel=normal
    allow-from=0.0.0.0/0
    webserver-allow-from=0.0.0.0/0
    webserver-address=0.0.0.0
    webserver=yes
    distributor-threads=4
    dnssec-log-bogus=true
    forward-zones=samplezone.com=xxx.xxx.xxx.xxx;xxx.xxx.xxx.xxx, google.es=8.8.8.8