apiVersion: v1
kind: ConfigMap
metadata:
  name: powerdns-clients-dist
  namespace: powerdns-clients-<ENV_ROLE>
data:
  dnsdist.conf: |
    setLocal('0.0.0.0:5353')
    newServer({address="xxx.xxx.xxx.xxx:5353"})
    setACL('0.0.0.0/0')