FROM dist-base as package-builder
ARG APT_URL
RUN apt-get -y install devscripts dpkg-dev build-essential python3

RUN mkdir /dist /pdns
WORKDIR /pdns

ADD builder/helpers/ /pdns/builder/helpers/

# Used for -p option to only build specific packages
ARG BUILDER_PACKAGE_MATCH

ARG BUILDER_VERSION
ARG BUILDER_RELEASE

COPY --from=sdist /sdist /sdist

RUN tar xvf /sdist/pdns-${BUILDER_VERSION}.tar.bz2
