FROM alpine:3.21 AS pdns-recursor
ARG BUILDER_CACHE_BUSTER=

RUN apk add --no-cache gcc g++ make tar autoconf automake protobuf-dev lua-dev \
                       libtool file boost-dev curl openssl-dev ragel python3 \
                       flex bison git bash jq meson cargo

COPY . /pdns-recursor
WORKDIR /pdns-recursor

#ADD builder-support/helpers/ /pdns/builder-support/helpers/
RUN cd /pdns-recursor/builder-support/helpers/ && \
    ./install_rust.sh

RUN mkdir /sdist

ARG BUILDER_VERSION

RUN cd /pdns-recursor/pdns/recursordist && \
    meson setup /tmp/rec-meson-dist-build && \
    meson dist -C /tmp/rec-meson-dist-build --no-tests

RUN cp /tmp/rec-meson-dist-build/meson-dist/pdns-recursor-${BUILDER_VERSION}.tar.xz /sdist/
