#!/bin/sh
cleandig a.host.test.dyndns ANY dnssec hidesoadetails
cleandig b.host.test.dyndns ANY dnssec hidesoadetails
cleandig c.host.test.dyndns ANY dnssec hidesoadetails
cleandig d.host.test.dyndns ANY dnssec hidesoadetails
cleandig e.host.test.dyndns ANY dnssec hidesoadetails
cleandig f.host.test.dyndns ANY dnssec hidesoadetails
cleandig a.a.host.test.dyndns ANY dnssec hidesoadetails
cleandig b.b.host.test.dyndns ANY dnssec hidesoadetails
cleandig c.c.host.test.dyndns ANY dnssec hidesoadetails
cleandig d.d.host.test.dyndns ANY dnssec hidesoadetails
cleandig e.e.host.test.dyndns ANY dnssec hidesoadetails

nsupdate <<! | sed 's/\, id:.*/ ID_REPLACED/'
server $nameserver $port
zone test.dyndns
update add c.host.test.dyndns 3600 NS ns1.c.host.test.dyndns
update add ns1.c.host.test.dyndns 3600 A 127.0.0.2
send
answer
!

cleandig a.host.test.dyndns ANY dnssec hidesoadetails
cleandig b.host.test.dyndns ANY dnssec hidesoadetails
cleandig c.host.test.dyndns ANY dnssec hidesoadetails
cleandig d.host.test.dyndns ANY dnssec hidesoadetails
cleandig e.host.test.dyndns ANY dnssec hidesoadetails
cleandig f.host.test.dyndns ANY dnssec hidesoadetails
cleandig a.a.host.test.dyndns ANY dnssec hidesoadetails
cleandig b.b.host.test.dyndns ANY dnssec hidesoadetails
cleandig c.c.host.test.dyndns ANY dnssec hidesoadetails
cleandig d.d.host.test.dyndns ANY dnssec hidesoadetails
cleandig e.e.host.test.dyndns ANY dnssec hidesoadetails

nsupdate <<! | sed 's/\, id:.*/ ID_REPLACED/'
server $nameserver $port
zone test.dyndns
update delete c.host.test.dyndns NS
send
answer
!

cleandig a.host.test.dyndns ANY dnssec hidesoadetails
cleandig b.host.test.dyndns ANY dnssec hidesoadetails
cleandig c.host.test.dyndns ANY dnssec hidesoadetails
cleandig d.host.test.dyndns ANY dnssec hidesoadetails
cleandig e.host.test.dyndns ANY dnssec hidesoadetails
cleandig f.host.test.dyndns ANY dnssec hidesoadetails
cleandig a.a.host.test.dyndns ANY dnssec hidesoadetails
cleandig b.b.host.test.dyndns ANY dnssec hidesoadetails
cleandig c.c.host.test.dyndns ANY dnssec hidesoadetails
cleandig d.d.host.test.dyndns ANY dnssec hidesoadetails
cleandig e.e.host.test.dyndns ANY dnssec hidesoadetails

nsupdate <<! | sed 's/\, id:.*/ ID_REPLACED/'
server $nameserver $port
zone test.dyndns
update delete ns1.c.host.test.dyndns A
send
answer
!

cleandig a.host.test.dyndns ANY dnssec hidesoadetails
cleandig b.host.test.dyndns ANY dnssec hidesoadetails
cleandig c.host.test.dyndns ANY dnssec hidesoadetails
cleandig d.host.test.dyndns ANY dnssec hidesoadetails
cleandig e.host.test.dyndns ANY dnssec hidesoadetails
cleandig f.host.test.dyndns ANY dnssec hidesoadetails
cleandig a.a.host.test.dyndns ANY dnssec hidesoadetails
cleandig b.b.host.test.dyndns ANY dnssec hidesoadetails
cleandig c.c.host.test.dyndns ANY dnssec hidesoadetails
cleandig d.d.host.test.dyndns ANY dnssec hidesoadetails
cleandig e.e.host.test.dyndns ANY dnssec hidesoadetails
