FROM {{ os_image }}:{{ os_version }}

{% if os_version == '8' or os_version == '9' %}
RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ os_version }}.noarch.rpm bind-utils
{% endif %}

{% if os_version == '7' %}
RUN yum install -y yum-plugin-priorities
{% endif %}

{% if release == 'dnsdist-15' and os_version == '8' %}
RUN dnf install -y 'dnf-command(config-manager)'
RUN dnf config-manager --set-enabled powertools
{% endif %}

RUN curl -o /etc/yum.repos.d/powerdns-{{ release }}.repo https://repo.powerdns.com/repo-files/{{ os }}-{{ release }}.repo
RUN yum install --assumeyes {%- if os_version == '8' %} --nobest{% endif %} {{ pkg }}

{% if release.startswith('rec-') %}
RUN mkdir /var/run/pdns-recursor
{% endif %}

CMD {{ cmd }} --version

