FROM {{ os_image }}:{{ os_version }}

RUN yum install -y oracle-epel-release-el{{ os_version }} bind-utils

{% if release == 'dnsdist-15' and os_version == '8' %}
RUN dnf install -y 'dnf-command(config-manager)'
RUN dnf config-manager --set-enabled powertools
{% endif %}

RUN curl -o /etc/yum.repos.d/powerdns-{{ release }}.repo https://repo.powerdns.com/repo-files/{{ os }}-{{ release }}.repo
RUN yum install --assumeyes {%- if os_version == '8' %} --nobest{% endif %} {{ pkg }}

{% if release.startswith('rec-') %}
RUN mkdir /var/run/pdns-recursor
{% endif %}

CMD {{ cmd }} --version

