site_name: dnsdist
repo_url: https://github.com/PowerDNS/pdns
docs_dir: markdown
site_dir: html
theme: bootstrap
extra_css: [extra.css]
pages:
  - dnsdist:
    - Homepage: index.md
    - Introduction: introduction.md
    - Screenshots: screenshots.md
  - Download: download.md
  - Changelog: changelog.md
  - Documentation:
    - All documentation: README.md
    - dnsdist.1 manpage: dnsdist.1.md
