#!/bin/sh

mysqldiff

$PDNSUTIL --config-dir=. --config-name=$backend increase-serial test.dyndns

mysqldiff 1 "Check that test.dyndns. still has a valid ordername"

# restore old SOA
$PDNSUTIL --config-dir=. --config-name=$backend \
    replace-rrset test.dyndns @ SOA "ns1.test.dyndns ahu.example.dyndns 2012060701 28800 7200 604800 86400" \
    > /dev/null
