#!/bin/sh
cleandig test.dyndns SOA hidesoadetails

cleannsupdate <<!
server $nameserver $port
zone test.dyndns
update add test.dyndns. 3600 SOA ns2.test.dyndns. ahu.example.dyndns. 2050101000 28800 7200 604800 86400
send
answer
!

cleandig test.dyndns SOA

cleannsupdate <<!
server $nameserver $port
zone test.dyndns
update add test.dyndns. 3600 SOA ns2.test.dyndns. ahu.example.dyndns. 2050101000 28800 7200 604800 86400
send
answer
!

cleandig test.dyndns SOA

cleannsupdate <<!
server $nameserver $port
zone test.dyndns
update add test.dyndns. 3600 SOA ns2.test.dyndns. ahu.example.dyndns. 2050100999 28800 7200 604800 86400
send
answer
!

cleandig test.dyndns SOA

cleannsupdate <<!
server $nameserver $port
zone test.dyndns
update add test.dyndns. 3600 SOA ns2.test.dyndns. ahu.example.dyndns. 2050101001 28800 7200 604800 86400
send
answer
!

cleandig test.dyndns SOA
