#!/bin/sh

cleandig test.dyndns SOA hidesoadetails

nsupdate <<! | sed 's/\, id:.*/ ID_REPLACED/'
server $nameserver $port
zone test.dyndns
update delete test.dyndns. SOA
send
answer
!

cleandig test.dyndns SOA hidesoadetails


