#!/bin/sh

cleandig test.dyndns SOA hidesoadetails

cleannsupdate <<!
server $nameserver $port
zone test.dyndns
update delete test.dyndns. SOA
send
answer
!

cleandig test.dyndns SOA hidesoadetails


