#!/bin/sh
set -e
set -x

. ./vars

if [ -z "$PREFIX" ] 
then
    echo "config not found or PREFIX not set"
    exit 1
fi

testsdir=.
export testsdir

nameserver=$PREFIX.9 port=53 ../regression-tests/runtests
context=recursor ../regression-tests/toxml
