#!/bin/sh
set -ex
cp -f ../regression-tests/zones/test.dyndns.orig ../regression-tests/zones/test.dyndns
export testsdir=$(pwd)
../regression-tests/runtests
../regression-tests/toxml

failed_tests=`wc -l failed_tests | cut -f 1 -d ' '`
if [ $failed_tests = 0 ];
then
	exit 0;
else
	for t in `cat failed_tests`; do
		cat $t/diff
	done

	exit 1;
fi
