#!/bin/sh

# The first invocation of pdnsutil is redirected to /dev/null to hide the
# "local files have been created" message if using lmdb as backend.
# All other pdnsutil invocation have the Ueberbackend destructor messages from
# --enable-verbose-logging removed.
# Invocations which will output zone contents are passed through sort(1), as
# the order of entries for records having multiple entries is backend-specific
# and not guaranteed to be in any particular order.

pdnsutil_wrapper() {
$PDNSUTIL --config-dir=. --config-name=$backend $* 2>&1 | egrep -v 'destructor'
}

pdnsutil_wrapper create-zone bug.less > /dev/null
pdnsutil_wrapper add-record bug.less cname CNAME host 
pdnsutil_wrapper add-record bug.less host A 127.0.0.1
# Duplicate records should be omitted
pdnsutil_wrapper add-record bug.less host2 A 127.0.0.2 127.0.0.2
# Can't add non-CNAME record to a CNAME record
pdnsutil_wrapper add-record bug.less cname A 127.0.0.1
# Can't add CNAME record if other records exist
pdnsutil_wrapper add-record bug.less host CNAME host2
# Adding existing record should ignore duplicates
pdnsutil_wrapper add-record bug.less host2 A 127.0.0.2 127.0.0.3 | LC_ALL=C sort

# Display zone contents for final verification
pdnsutil_wrapper list-zone bug.less | LC_ALL=C sort

# Delete this non-standard zone, so that the result of the zone-variants
# test do not vary if this particular test is skipped.
pdnsutil_wrapper delete-zone bug.less > /dev/null
