#!/bin/sh

if [ ! -d .venv ]; then
	virtualenv -p python2 .venv
fi
. .venv/bin/activate
python -V
pip install -r requirements.txt

mkdir -p configs

export PDNSRECURSOR=${PDNSRECURSOR:-${PWD}/../pdns/recursordist/pdns_recursor}
export RECCONTROL=${RECCONTROL:-${PWD}/../pdns/recursordist/rec_control}

set -e
if [ "${PDNS_DEBUG}" = "YES" ]; then
  set -x
fi
nosetests --with-xunit $@
