#!/bin/sh
cleandig test.dyndns MX

cleannsupdate <<!
server $nameserver $port
zone test.dyndns
update add test.dyndns. 3000 MX 10 host-1.test.dyndns.
send
answer
!

cleandig test.dyndns MX

cleannsupdate <<!
server $nameserver $port
zone test.dyndns
update add test.dyndns. 3600 MX 10 host-1.test.dyndns.
send
answer
!

cleandig test.dyndns MX
