#!/bin/sh

mysqldiff

cleannsupdate <<!
server $nameserver $port
zone test.dyndns
update add a.b.c.d.e.f.test.dyndns. 3600 A 127.0.0.1
update add a.b.d.e.f.test.dyndns. 3600 A 127.0.0.1
send
answer
!

mysqldiff 1 "Check if records are added"


cleannsupdate <<!
server $nameserver $port
zone test.dyndns
update delete a.b.c.d.e.f.test.dyndns. 3600 A 127.0.0.1
send
answer
!

mysqldiff 2 "Check if a.b.c.d.e.f is removed correctly"

cleannsupdate <<!
server $nameserver $port
zone test.dyndns
update delete a.b.d.e.f.test.dyndns. 3600 A 127.0.0.1
send
answer
!

mysqldiff 3 "Check if everything is removed correctly"
