#!/usr/bin/env bash
PDNS=${PDNS:-${PWD}/../../../pdns/pdns_server}
MODULEDIR=

if [ -e ../.libs/libluabackend.so ]
then
	MODULEDIR=--module-dir=../.libs/
fi

$PDNS --no-config --daemon=no --local-port=5300 --socket-dir=./  \
--no-shuffle --launch=lua --loglevel=9 --config-dir=./ \
--cache-ttl=0 --negquery-cache-ttl=0 --query-cache-ttl=0 \
$MODULEDIR --lua-filename=./pdns-luabackend.lua
