#!/bin/bash

./pdns &

sleep 2 # give some time to start

./runtest.pl
testres=$?

./pdns_control quit

sleep 2 # and some time to shut down

jobs -lr
[ -n "$(jobs -pr)" ] && jobs -x kill

echo "all done? $testres"

exit $testres
