#!/bin/bash
WWWPREFIX=. 
WSIZE=800
HSIZE=250

function makeGraphs()
{
  rrdtool graph --start -$1 $WWWPREFIX/questions-$2.png -w $WSIZE -h $HSIZE -l 0\
	-t "Question and answer counts per second" \
	-v "packets" \
	DEF:questions=pdns_recursor.rrd:questions:AVERAGE  \
        DEF:nxdomainanswers=pdns_recursor.rrd:nxdomain-answers:AVERAGE \
        DEF:noerroranswers=pdns_recursor.rrd:noerror-answers:AVERAGE \
        DEF:servfailanswers=pdns_recursor.rrd:servfail-answers:AVERAGE \
        LINE2:questions#0000ff:"questions/s"\
        AREA:noerroranswers#00ff00:"noerror answers/s"  \
        STACK:nxdomainanswers#ffa500:"nxdomain answers/s"\
        STACK:servfailanswers#ff0000:"servfail answers/s"

  rrdtool graph --start -$1 $WWWPREFIX/tcp-questions-$2.png -w $WSIZE -h $HSIZE -l 0\
	-t "TCP question and answer counts per second" \
	-v "packets" \
	DEF:tcpquestions=pdns_recursor.rrd:tcp-questions:AVERAGE  \
        LINE2:tcpquestions#0000ff:"questions/s"\

  rrdtool graph --start -$1 $WWWPREFIX/latencies-$2.png -w $WSIZE -h $HSIZE -l 0\
	-t "Questions answered within latency" \
	-v "questions" \
	DEF:questions=pdns_recursor.rrd:questions:AVERAGE  \
        DEF:answers01=pdns_recursor.rrd:answers0-1:AVERAGE \
        DEF:answers110=pdns_recursor.rrd:answers1-10:AVERAGE \
        DEF:answers10100=pdns_recursor.rrd:answers10-100:AVERAGE \
        DEF:answers1001000=pdns_recursor.rrd:answers100-1000:AVERAGE \
        DEF:answersslow=pdns_recursor.rrd:answers-slow:AVERAGE \
        LINE2:questions#0000ff:"questions/s" \
        AREA:answers01#00ff00:"<1 ms" \
        STACK:answers110#0000ff:"<10 ms" \
        STACK:answers10100#00ffff:"<100 ms" \
        STACK:answers1001000#ffff00:"<1000 ms" \
        STACK:answersslow#ff0000:">1000 ms"       

  rrdtool graph --start -$1 $WWWPREFIX/qoutq-$2.png -w $WSIZE -h $HSIZE -l 0 \
	-t "Questions/outqueries counts per second" \
	-v "packets" \
	DEF:questions=pdns_recursor.rrd:questions:AVERAGE  \
        DEF:alloutqueries=pdns_recursor.rrd:all-outqueries:AVERAGE \
        LINE2:questions#ff0000:"questions/s"\
        LINE2:alloutqueries#00ff00:"outqueries/s"

  rrdtool graph --start -$1 $WWWPREFIX/qa-latency-$2.png -w $WSIZE -h $HSIZE -l 0 \
	-t "Questions/answer latency in milliseconds" \
	-v "msec" \
	DEF:qalatency=pdns_recursor.rrd:qa-latency:AVERAGE  \
	CDEF:mqalatency=qalatency,1000,/ \
        LINE2:mqalatency#ff0000:"questions/s"


  rrdtool graph --start -$1 $WWWPREFIX/timeouts-$2.png -w $WSIZE -h $HSIZE -l 0\
	-t "Outqueries/timeouts counts per second" \
	-v "events" \
	DEF:alloutqueries=pdns_recursor.rrd:all-outqueries:AVERAGE  \
        DEF:outgoingtimeouts=pdns_recursor.rrd:outgoing-timeouts:AVERAGE \
        DEF:throttledout=pdns_recursor.rrd:throttled-out:AVERAGE \
        LINE2:alloutqueries#ff0000:"outqueries/s"\
        LINE2:outgoingtimeouts#00ff00:"outgoing timeouts/s"\
        LINE2:throttledout#0000ff:"throttled outqueries/s"
	

  rrdtool graph --start -$1 $WWWPREFIX/caches-$2.png -w $WSIZE -h $HSIZE -l 0\
	-t "Cache sizes" \
	-v "entries" \
	DEF:cacheentries=pdns_recursor.rrd:cache-entries:AVERAGE  \
	DEF:negcacheentries=pdns_recursor.rrd:negcache-entries:AVERAGE  \
	DEF:nsspeedsentries=pdns_recursor.rrd:nsspeeds-entries:AVERAGE  \
	DEF:throttleentries=pdns_recursor.rrd:throttle-entries:AVERAGE  \
        LINE2:cacheentries#ff0000:"cache entries" \
        LINE2:negcacheentries#0000ff:"negative cache entries" \
        LINE2:nsspeedsentries#00ff00:"NS speeds entries" \
        LINE2:throttleentries#00ff00:"throttle map entries" 
        

  rrdtool graph --start -$1 $WWWPREFIX/caches2-$2.png -w $WSIZE -h $HSIZE -l 0\
	-t "Cache sizes" \
	-v "entries" \
	DEF:negcacheentries=pdns_recursor.rrd:negcache-entries:AVERAGE  \
	DEF:nsspeedsentries=pdns_recursor.rrd:nsspeeds-entries:AVERAGE  \
	DEF:throttleentries=pdns_recursor.rrd:throttle-entries:AVERAGE  \
        LINE2:negcacheentries#0000ff:"negative cache entries" \
        LINE2:nsspeedsentries#00ff00:"NS speeds entries" \
        LINE2:throttleentries#ffa000:"throttle map entries" 

  rrdtool graph --start -$1 $WWWPREFIX/load-$2.png -w $WSIZE -h $HSIZE -l 0\
	-v "MThreads" \
	-t "Concurrent queries" \
	DEF:concurrentqueries=pdns_recursor.rrd:concurrent-queries:AVERAGE  \
        LINE2:concurrentqueries#0000ff:"concurrent queries"
        
  rrdtool graph --start -$1 $WWWPREFIX/hitrate-$2.png -w $WSIZE -h $HSIZE -l 0\
	-v "percentage" \
	-t "cache hits" \
	DEF:cachehits=pdns_recursor.rrd:cache-hits:AVERAGE  \
	DEF:cachemisses=pdns_recursor.rrd:cache-misses:AVERAGE  \
	DEF:usermsec=pdns_recursor.rrd:user-msec:AVERAGE \
	DEF:sysmsec=pdns_recursor.rrd:sys-msec:AVERAGE \
	CDEF:perc=cachehits,100,*,cachehits,cachemisses,+,/    \
	CDEF:userperc=usermsec,10,/ \
	CDEF:sysperc=sysmsec,10,/ \
        LINE2:perc#0000ff:"percentage cache hits"  \
        AREA:userperc#ff0000:"user cpu percentage" \
        STACK:sysperc#00ff00:"system cpu percentage" \
        COMMENT:"\l" \
        COMMENT:"Cache hits " \
        GPRINT:perc:AVERAGE:"avg %-3.1lf%%\t" \
        GPRINT:perc:LAST:"last %-3.1lf%%\t" \
        GPRINT:perc:MAX:"max %-3.1lf%%" \
        COMMENT:"\l" \
        COMMENT:"System cpu " \
        GPRINT:sysperc:AVERAGE:"avg %-3.1lf%%\t" \
        GPRINT:sysperc:LAST:"last %-3.1lf%%\t" \
        GPRINT:sysperc:MAX:"max %-3.1lf%%\t" \
        COMMENT:"\l" \
        COMMENT:"User cpu   " \
        GPRINT:userperc:AVERAGE:"avg %-3.1lf%%\t" \
        GPRINT:userperc:LAST:"last %-3.1lf%%\t" \
        GPRINT:userperc:MAX:"max %-3.1lf%%"

}
	
makeGraphs 6h 6h
makeGraphs 24h day
#makeGraphs 7d week
#makeGraphs 1m month
#makeGraphs 1y year


