#!/bin/sh
ldns-verify-zone -h | head -n 1
for zone in $(grep zone named.conf  | cut -f2 -d\" | grep -v '^example.com$')
do
	TFILE=$(mktemp)
	dig axfr $zone @$nameserver -p $port | ldns-read-zone -z > $TFILE
	for validator in "ldns-verify-zone -V2" validns jdnssec-verifyzone
	do
		echo --- $validator $zone
		$validator $TFILE 2>&1
		RETVAL=$?
		echo RETVAL: $RETVAL
		if [ $RETVAL -gt 0 ]
		then
			echo $validator reported error, full zone content:
			echo ---
			cat $TFILE
			echo --- end of zone content
		fi
		echo
	done
	
	rm -f $TFILE
done
