#!/bin/sh
set -e

case "$1" in
  configure)
    if [ -z "`getent group pdns`" ]; then
      addgroup --system pdns
    fi
    if [ -z "`getent passwd pdns`" ]; then
      adduser --system --home /var/spool/powerdns --shell /bin/false --ingroup pdns --disabled-password --disabled-login --gecos "PowerDNS" pdns
    fi
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

# Startup errors should never cause dpkg to fail.
initscript_error() {
    return 0
}

#DEBHELPER#

exit 0
