#!/bin/sh
set -e
set -x
cd pdns-recursor-$1
export DEBFULLNAME="PowerDNS.COM BV"
if echo $1 | grep -q ^git
then
	DEBPKGNAME=pdns-recursor_0.0-$1
else
	DEBPKGNAME=pdns-recursor_$1
fi

export LUA=1
export STATIC=semi
dpkg-buildpackage -uc -us 
fakeroot rpmbuild -bb ../pdns-recursor.spec 
