#!/bin/sh
set -e

if [ "$CXX" = "" ]; then
  CXX="g++"
fi

if [ "$STATIC" = "" ]; then
  STATIC="no"
fi

set -u

LD_RELRO=""
CF_PIE=""
LD_PIE=""
CF_FORTIFY=""
CF_STACK=""

test_flags() {
  # test for relocation

  if [ `uname -s` = 'SunOS' -o `uname -s` = 'FreeBSD' ]; then
    return
  fi

  if $CXX -Wl,-help 2>/dev/null | grep 'z relro' >/dev/null; then
    LD_RELRO="-Wl,-z -Wl,relro"
    if $CXX -Wl,-help 2>/dev/null | grep 'z now' >/dev/null; then
      LD_RELRO="$LD_RELRO -Wl,-z -Wl,now"
    fi
    export LD_RELRO
  fi

  src=conftest.cc
  cat >$src <<EOF
int
main ()
{
  return 0;
}
EOF

  # test for PIE
  if $CXX $src -c -o a.out -fPIE -fPIC -DPIE; then
    if [ "$STATIC" != "semi" ] && [ "$STATIC" != "full" ] && $CXX -pie -o a2.out a.out; then
      CF_PIE="-fPIE -fPIC -DPIE"
      LD_PIE="-pie"
    fi
  fi

  # test for fortified source
  if $CXX $src -c -o a.out -O3 -D_FORTIFY_SOURCE=2; then
    CF_FORTIFY="-D_FORTIFY_SOURCE=2"
  fi

  # test for stack protector
  if $CXX $src -c -o a.out -O3 -fstack-protector; then
    CF_STACK="-fstack-protector"
    if $CXX $src -c -o a.out -O3 -fstack-protector --param ssp-buffer-size=4; then
      CF_STACK="$CF_STACK --param ssp-buffer-size=4"
    fi
  fi

  rm -f $src a.out a2.out
}

test_flags

sed -e "s/@LD_RELRO@/$LD_RELRO/g" -e "s/@LD_PIE@/$LD_PIE/g" -e "s/@CF_PIE@/$CF_PIE/g" -e "s/@CF_FORTIFY@/$CF_FORTIFY/g" -e "s/@CF_STACK@/$CF_STACK/g" < Makefile.in > Makefile

echo Testing dependencies and compiler.

MAKE=`which gmake || echo make`

echo Using $MAKE to build
$MAKE basic_checks
