#!/usr/bin/env bash

set -e

VERSION=3.5-rc2

INCLUDES="iputils.hh arguments.hh base64.hh zoneparser-tng.hh \
rcpgenerator.hh lock.hh dnswriter.hh  dnsrecords.hh dnsparser.hh utility.hh \
recursor_cache.hh rec_channel.hh qtype.hh misc.hh dns.hh syncres.hh \
sstuff.hh mtasker.hh mtasker.cc lwres.hh logger.hh ahuexception.hh \
mplexer.hh win32_mtasker.hh win32_utility.cc ntservice.hh singleton.hh \
recursorservice.hh dns_random.hh lua-pdns.hh lua-recursor.hh namespaces.hh \
recpacketcache.hh base32.hh cachecleaner.hh json.hh"

CFILES="syncres.cc  misc.cc unix_utility.cc qtype.cc \
logger.cc arguments.cc  lwres.cc pdns_recursor.cc  \
recursor_cache.cc  dnsparser.cc dnswriter.cc  dnsrecords.cc  rcpgenerator.cc  \
base64.cc  zoneparser-tng.cc  rec_channel.cc rec_channel_rec.cc rec_control.cc \
selectmplexer.cc epollmplexer.cc kqueuemplexer.cc portsmplexer.cc pdns_hw.cc \
win32_mtasker.cc win32_rec_channel.cc win32_logger.cc ntservice.cc \
recursorservice.cc sillyrecords.cc lua-pdns.cc lua-recursor.cc randomhelper.cc \
devpollmplexer.cc recpacketcache.cc dns.cc reczones.cc base32.cc nsecrecords.cc \
json.cc json_ws.cc json_ws.hh"

cd docs
make pdns_recursor.1 rec_control.1
cd ..

DIRNAME=pdns-recursor-$VERSION
rm -rf $DIRNAME
mkdir  $DIRNAME
cp dnslabeltext.rl $DIRNAME/
ragel dnslabeltext.rl -o $DIRNAME/dnslabeltext.cc
cp $INCLUDES $CFILES $DIRNAME
cp Makefile-recursor $DIRNAME/Makefile
cp Makefile-recursor.win32 $DIRNAME/Makefile.win32
cp README-recursor $DIRNAME/README
cp ../COPYING $DIRNAME/
cp config-recursor.h $DIRNAME/config.h
mkdir -p $DIRNAME/ext/rapidjson/include/rapidjson/internal
cp -a ext/rapidjson/include/rapidjson/*.h $DIRNAME/ext/rapidjson/include/rapidjson/
cp -a ext/rapidjson/include/rapidjson/internal/*.h $DIRNAME/ext/rapidjson/include/rapidjson/internal
mkdir $DIRNAME/rrd
cp tools/rrd/{create,update,makegraphs,index.html} $DIRNAME/rrd
mkdir $DIRNAME/aes
cp aes/*.{c,cc,h} $DIRNAME/aes
cp pdns-recursor.init.d $DIRNAME
cp docs/pdns_recursor.1 docs/rec_control.1 $DIRNAME
cp configure-recursor $DIRNAME/configure
cp powerdns-example-script.lua $DIRNAME
mkdir -p $DIRNAME/contrib
cp ../contrib/systemd-pdns-recursor.service $DIRNAME/contrib

mkdir -p $DIRNAME/sysdeps-recursor
rm -f sysdeps-recursor/*~
cp  sysdeps-recursor/* $DIRNAME/sysdeps-recursor
cp "PowerDNS Recursor.vcproj" $DIRNAME/
tar cf $DIRNAME.tar $DIRNAME
bzip2 -f $DIRNAME.tar # .. solaris

zip -q $DIRNAME.zip $DIRNAME/*

