#!/usr/bin/env bash

set -e

ragel dnslabeltext.rl -o dnslabeltext.cc

## The following lines will be patched by set-version-recursor.
VERSION=""
DIST_HOST=""
## End patch area.

if [ -z "$VERSION" ]; then
  VERSION=$(git describe --always --dirty=+ 2>/dev/null || true)
  if [ -z "$VERSION" ]; then
    VERSION="UNKNOWN"
  else
    VERSION="git-"$VERSION
  fi
  DIST_HOST="$(id -u -n)@$(hostname -f || hostname)"
fi

INCLUDES="iputils.hh arguments.hh base64.hh zoneparser-tng.hh \
rcpgenerator.hh lock.hh dnswriter.hh  dnsrecords.hh dnsparser.hh utility.hh \
recursor_cache.hh rec_channel.hh qtype.hh misc.hh dns.hh syncres.hh \
sstuff.hh mtasker.hh mtasker.cc lwres.hh logger.hh pdnsexception.hh \
mplexer.hh \
dns_random.hh lua-pdns.hh lua-recursor.hh namespaces.hh \
recpacketcache.hh base32.hh cachecleaner.hh json.hh version.hh"

CFILES="syncres.cc  misc.cc unix_utility.cc qtype.cc \
logger.cc arguments.cc  lwres.cc pdns_recursor.cc  \
recursor_cache.cc  dnsparser.cc dnswriter.cc  dnsrecords.cc  rcpgenerator.cc  \
base64.cc  zoneparser-tng.cc  rec_channel.cc rec_channel_rec.cc rec_control.cc \
selectmplexer.cc epollmplexer.cc kqueuemplexer.cc portsmplexer.cc pdns_hw.cc \
sillyrecords.cc lua-pdns.cc lua-recursor.cc randomhelper.cc \
devpollmplexer.cc recpacketcache.cc dns.cc reczones.cc base32.cc nsecrecords.cc \
dnslabeltext.cc json.cc json_ws.cc json_ws.hh version.cc dns_random.cc"

cd docs
make pdns_recursor.1 rec_control.1
cd ..

DIRNAME=pdns-recursor-$VERSION
rm -rf $DIRNAME
mkdir  $DIRNAME
cp $INCLUDES $CFILES $DIRNAME
cp Makefile-recursor $DIRNAME/Makefile
cp README-recursor $DIRNAME/README
cp ../COPYING ../NOTICE $DIRNAME/
cp config-recursor.h $DIRNAME/config.h
cat >>$DIRNAME/config.h <<EOF
#define VERSION "$VERSION"
#define DIST_HOST "$DIST_HOST"
EOF
mkdir -p $DIRNAME/ext/rapidjson/include/rapidjson/internal
cp -a ext/rapidjson/include/rapidjson/*.h $DIRNAME/ext/rapidjson/include/rapidjson/
cp -a ext/rapidjson/include/rapidjson/internal/*.h $DIRNAME/ext/rapidjson/include/rapidjson/internal
mkdir -p $DIRNAME/ext/polarssl-1.3.2/include/polarssl
cp -a ext/polarssl-1.3.2/include/polarssl/config.h ext/polarssl-1.3.2/include/polarssl/aes.h ext/polarssl-1.3.2/include/polarssl/padlock.h $DIRNAME/ext/polarssl-1.3.2/include/polarssl
mkdir -p $DIRNAME/ext/polarssl-1.3.2/library
cp -a ext/polarssl-1.3.2/library/aes.c ext/polarssl-1.3.2/library/padlock.c $DIRNAME/ext/polarssl-1.3.2/library
mkdir $DIRNAME/rrd
cp tools/rrd/{create,update,makegraphs,index.html} $DIRNAME/rrd
cp pdns-recursor.init.d $DIRNAME
cp docs/pdns_recursor.1 docs/rec_control.1 $DIRNAME
cp configure-recursor $DIRNAME/configure
cp powerdns-example-script.lua $DIRNAME
mkdir -p $DIRNAME/contrib
cp ../contrib/systemd-pdns-recursor.service $DIRNAME/contrib
mkdir -p $DIRNAME/build-scripts/redhat
cp ../build-scripts/redhat/pdns-recursor-test.spec $DIRNAME/build-scripts/redhat

mkdir -p $DIRNAME/sysdeps
rm -f sysdeps-recursor/*~
cp  sysdeps-recursor/* $DIRNAME/sysdeps
tar cf $DIRNAME.tar $DIRNAME
bzip2 -f $DIRNAME.tar # .. solaris

zip -q $DIRNAME.zip $DIRNAME/*

