#!/usr/bin/env bash

if [ ! -d .venv ]; then
	virtualenv .venv
fi
. .venv/bin/activate
python -V
pip install -r requirements.txt

if [ -z "${DNSDISTBIN}" ]; then
    DNSDISTBIN=$(ls ../pdns/dnsdistdist/dnsdist-*/dnsdist)
fi
export DNSDISTBIN

set -e
if [ "${PDNS_DEBUG}" = "YES" ]; then
  set -x
fi
nosetests --with-xunit
