#!/bin/bash

if [ "$1" = "--cflags" ]; then
  FLAGS=$(/usr/bin/net-snmp-config --cflags)
  MYFLAGS=""
  for flag in $FLAGS; do
    if [[ "$flag" =~ -DNETSNMP* ]]; then
      MYFLAGS="$MYFLAGS $flag"
    fi
  done
  echo "$MYFLAGS"
  exit 0

elif [ "$1" = "--netsnmp-agent-libs" ]; then
  /usr/bin/net-snmp-config "$@"
  exit $?

else
  echo "E: debian/configure-helpers/net-snmp-config: unknown flag $1" >&2
  exit 1
fi
