#!/bin/sh
cleandig cname1.test.dyndns CNAME

cleannsupdate <<!
server $nameserver $port
zone test.dyndns
update add cname1.test.dyndns. 3600 CNAME host-2.test.dyndns.
send
answer
!

cleandig cname1.test.dyndns CNAME

cleannsupdate <<!
server $nameserver $port
zone test.dyndns
update add cname1.test.dyndns. 3600 CNAME host-1.test.dyndns.
send
answer
!

cleandig cname1.test.dyndns CNAME
