#!/usr/bin/env bash
set -e

if [ ! -d .venv ]; then
  python3 -m venv .venv
fi
. .venv/bin/activate
python -V
pip install -r requirements.txt | cat

if [ -z "${IXFRDISTBIN}" ]; then
  IXFRDISTBIN=$(ls ../pdns/ixfrdist)
fi
export IXFRDISTBIN

set -e
if [ "${PDNS_DEBUG}" = "YES" ]; then
  set -x
fi

rm -rf ixfrdist.dir
mkdir ixfrdist.dir

pytest --junitxml=pytest.xml $@
