#!/bin/bash
TSTAMP=$(date +%s)
cd ../..

VARIABLES="questions cache-entries concurrent-queries\
	   nxdomain-answers noerror-answers\
	   servfail-answers tcp-outqueries\
	   outgoing-timeouts nsspeeds-entries negcache-entries all-outqueries throttled-out\
	   cache-hits cache-misses answers0-1 answers1-10 answers10-100 answers100-1000 answers-slow"

UVARIABLES=$(echo $VARIABLES | tr [a-z] [A-Z] | tr - _	)

./rec_control GET $VARIABLES |
(
  for a in $UVARIABLES
  do
	  read $a
  done
  cd - 
  rrdtool update pdns_recursor.rrd \
	-t \
	$(for a in $VARIABLES 
	do
		echo -n $a:
	done | sed 's/:$//' ) \
$TSTAMP$(
	for a in $UVARIABLES
	do
		echo -n :${!a}
	done)
)
