#!/bin/sh

export LC_ALL=C.UTF-8
export LANG=C.UTF-8

if [ -n "$1" ]
then
	DIR=$1/
fi

files=$(find ${DIR}html -type f \! -path '*non-min/*' \! -name '*~' | sort)
for a in $files
do
	c=$(echo $a | sed s:${DIR}html/:: | tr "/.-" "___")
        echo "static const unsigned char g${c}Data[] = {"
	gzip -9c "$a" | od -v -t x1 | sed  's/^[0-7]*//' | sed 's/\([0-9a-f][0-9a-f]\)/0x\1,/g'
	echo "};"
done

echo "static const std::map<std::string,std::string> g_urlmapgz = {"
for a in $files
do
	b=$(echo $a | sed s:${DIR}html/::g)
	c=$(echo $b | tr "/.-" "___")
	echo "{\"$b\", std::string((const char*)g${c}Data, sizeof(g${c}Data))},"
done
echo "};"
