#!/bin/sh
if [ -z "$1" ] || [ -z "$2" ]; then
  echo "Usage: $0 effective_tld_names.dat pubsuffix.cc"
  exit 1
fi
set -e
(echo "const char* g_pubsuffix[]={"; 
	for a in $(grep -v "//" "$1" | grep \\. | egrep "^[.0-9a-z-]*$")
	do 
		echo \"$a\",
	done 
echo "0};") > "$2"
