#!/bin/sh
if [ -z "$1" ]; then
  echo "Usage: $0 pubsuffix.cc"
  exit 1
fi
set -e
temp=$(mktemp pubsuffixXXXXXX)
curl -s -S https://publicsuffix.org/list/public_suffix_list.dat > $temp
(echo "const char* g_pubsuffix[]={";
	for a in $(grep -v "//" "$temp" | grep \\. | egrep "^[.0-9a-z-]*$")
	do
		echo \"$a\",
	done
echo "0};") > "$1"
rm -f "$temp"
