#!/bin/bash 

# Internal script used to build daily snapshots (if there is a change in svn, that is)

cd /home/ahu/auto-build
if [ -e pdns ] 
then
	cd pdns
	LATEST=$(svn info svn://svn.powerdns.com/pdns/ | awk  '/^Revision/ { print $2 }'  )
	CO=$(svn info . | awk  '/^Revision/ { print $2 }'  )
	if [ "$LATEST" -eq "$CO" -a -e ../pdns-static*$CO-1.i386.rpm ]
	then
		echo nothing to do
		exit
	fi
	cd ..
fi

# start out with virgin repo anyhow
rm -rf pdns
svn co svn://svn.powerdns.com/pdns/trunk/pdns
cd pdns
LATEST=$(svn info . | awk  '/^Revision/ { print $2 }'  )
DATE=$(date +%Y%m%d).$LATEST

build-scripts/set-version-auth "$DATE"

./bootstrap
fakeroot debian-pdns/rules binary-static
rm -rf debian-pdns/tmp/
./build-scripts/rpm-build-instruction
rm debian-pdns/.svn -rf
build-scripts/tar-gz-build-instruction
cd ..
mv pdns/*.tar.gz .
#ssh svn.powerdns.com mkdir /var/www/svn.powerdns.com/snapshots/$LATEST
echo rsync -v --bwlimit=75 pdns-static*$LATEST*{rpm,deb,tar.gz} svn.powerdns.com:/var/www/svn.powerdns.com/dnssec-wild-testing > boe
bash ./boe



