#!/bin/sh
set -e
set -x

if [ -z "$VERSION" ]; then
  VERSION=$(git describe --always --dirty=+ 2>/dev/null || true)
  if [ -z "$VERSION" ]; then
    VERSION="UNKNOWN"
  else
    VERSION="git-"$VERSION
  fi
else
  VERSION=$1
fi

DIST_HOST="$(id -u -n)@$(hostname -f 2>/dev/null || hostname 2>/dev/null || echo localhost)"

export DEBFULLNAME="PowerDNS.COM BV"
export DEBEMAIL="noreply@powerdns.com"
DEBPKGNAME=pdns-recursor_$VERSION

dh_make -s -f ../pdns-recursor-$VERSION.tar.bz2 -p $DEBPKGNAME < /dev/null
cp pdns-recursor.init.d debian/init.d
#[ -e debian/control ] || dh_make -e powerdns.support@powerdns.com -s -r cdbs  -f ../pdns-recursor-$VERSION.tar.bz2  < /dev/null
perl -i -pe 's/Description: <.*>/Description: extremely powerful and versatile recursing nameserver/' debian/control
# only to be nice to people usind the generated .dsc
perl -i -pe 's/(Build-Depends: .*)/$1, libboost-dev, libboost-serialization-dev, liblua5.2-0-dev/' debian/control
# Fix the rpm version number
perl -i -pe "s/Version: .*/Version: ${VERSION}/" pdns-recursor.spec
export LUA=1
export STATIC=semi
./configure
fakeroot debian/rules binary
fakeroot rpmbuild -bb pdns-recursor.spec
