#!/bin/sh

if [ "$0" != "./build-scripts/build-recursor-debian" ]; then
  echo "Please run me from the root checkout dir" >&2
  exit 1
fi

. build-scripts/functions.sh
TARBALLPREFIX=pdns-recursor

startup

set -e
set -x

cp_tarball_to_tmp

cd ${SRCDIR}

cat > debian/changelog << EOF
pdns-recursor (${VERSION}-${RELEASE}) unstable; urgency=medium

  * Automatic build

 -- PowerDNS.COM AutoBuilder <noreply@powerdns.com>  $(date -R)

EOF

PDNS_VERSION=$VERSION

. /etc/os-release
export ID="${ID}"
export VERSION_ID="${VERSION_ID}"

if [ ${ID} = "ubuntu" -a ${VERSION_ID} = "14.04" ]; then
  sed -i '/lib\/systemd\/system\/pdns-recursor@\?\.service/d' debian/pdns-recursor.install
fi

fakeroot debian/rules debian/control
fakeroot debian/rules binary

cd -

mv_debs_to_pwd
