#!/bin/sh

if [ "$0" != "./build-scripts/build-dnsdist-debian" ]; then
  echo "Please run me from the root checkout dir"
  exit 1
fi

. build-scripts/functions.sh
TARBALLPREFIX=dnsdist

startup

set -e
set -x

cp_tarball_to_tmp

cd ${SRCDIR}

cat > debian/changelog << EOF
dnsdist (${VERSION}-${RELEASE}) unstable; urgency=medium

  * Automatic build

 -- PowerDNS.COM AutoBuilder <noreply@powerdns.com>  $(date -R)

EOF

. /etc/os-release
export ID="${ID}"
export VERSION_ID="${VERSION_ID}"

if [ ${ID} = "ubuntu" -a ${VERSION_ID} = "14.04" ]; then
  rm -f debian/dnsdist.service
fi

fakeroot debian/rules debian/control
fakeroot debian/rules debian/dnsdist.install
fakeroot debian/rules binary

cd -

mv_debs_to_pwd
