#!/bin/sh

export DEBFULLNAME="PowerDNS.COM BV AutoBuilder"
export DEBEMAIL="noreply@powerdns.com"

if [ "$0" != "./build-scripts/build-auth-debian" ]; then
  echo "Please run me from the root checkout dir"
  exit 1
fi

if [ -z "$VERSION" ]; then
  echo 'Please set $VERSION' >&2
  exit 1
fi

if [ -z "$RELEASE" ];then
  echo 'Please set $RELEASE' >&2
  exit 1
fi

DISTDIR=${DISTDIR:=.}

set -e
set -x

rm -rf $DISTDIR/debian/
cp -r build-scripts/debian-authoritative $DISTDIR/debian

cd $DISTDIR

cat > debian/changelog << EOF
pdns (${VERSION}-${RELEASE}) unstable; urgency=medium

  * Automatic build

 -- ${DEBFULLNAME} <${DEBEMAIL}>  $(date -R)

EOF

PDNS_VERSION=$VERSION

. /etc/os-release
export ID="${ID}"
export VERSION_ID="${VERSION_ID}"

if [ ${ID} = "ubuntu" -a ${VERSION_ID} = "14.04" ]; then
  sed -i '/lib\/systemd\/system\/pdns@\?\.service/d' debian/pdns-server.install
fi

fakeroot debian/rules debian/control

if $(echo $PDNS_VERSION | grep -q -E '^0\.0\.'); then
  # make sure we don't break dependencies for master releases
  sed -i '/pdns-server (<< 3.4.6-2)/d' debian/control
fi

DH_OPTIONS=--parallel fakeroot debian/rules binary
