#!/bin/sh

if [ "$0" != "./build-scripts/build-auth-debian" ]; then
  echo "Please run me from the root checkout dir"
  exit 1
fi

. build-scripts/functions.sh
TARBALLPREFIX=pdns

startup

set -e
set -x

cp_tarball_to_tmp

cd ${SRCDIR}

cat > debian/changelog << EOF
pdns (${VERSION}-${RELEASE}) unstable; urgency=medium

  * Automatic build

 -- ${DEBFULLNAME} <${DEBEMAIL}>  $(date -R)

EOF

PDNS_VERSION=$VERSION

. /etc/os-release
export ID="${ID}"
export VERSION_ID="${VERSION_ID}"

if [ ${ID} = "ubuntu" ]; then
  if [ ${VERSION_ID} = "14.04" ]; then
    sed -i '/lib\/systemd\/system\/pdns@\?\.service/d' debian/pdns-server.install
  fi
  if [ $VERSION_ID} = "16.10" ];then
    sed -i 's!libzmq-dev!libzmq3-dev!' debian/control.in
  fi
fi

fakeroot debian/rules debian/control

if $(echo $PDNS_VERSION | grep -q -E '^0\.0\.'); then
  # make sure we don't break dependencies for master releases
  sed -i '/pdns-server (<< 3.4.6-2)/d' debian/control
fi

DH_OPTIONS=--parallel fakeroot debian/rules binary

cd -

mv_debs_to_pwd
