#!/usr/bin/env bash

set -e

if [ "$0" != "./build-scripts/dist-recursor" ]; then
  echo "Please run me from the root checkout dir"
  exit 1
fi
set -x

cd pdns/recursordist

autoreconf -vi
./configure
make dist
