#!/bin/bash -x
sudo apt-get update
# FIXME: Avoid GRUB related errors due to runner image configuration by removing it.
sudo dpkg --purge --force-all grub-efi-amd64-signed && sudo dpkg --purge --force-all shim-signed
sudo apt-get autoremove
sudo apt-get -qq -y dist-upgrade
sudo apt-get -qq -y --no-install-recommends install python3-pip
sudo pip3 install git+https://github.com/pyinvoke/invoke@faa5728a6f76199a3da1750ed952e7efee17c1da
