#!/bin/bash -x
sudo apt-get update
sudo apt-get -qq -y dist-upgrade
sudo apt-get -qq -y --no-install-recommends install python3-pip
sudo pip3 install git+https://github.com/pyinvoke/invoke@faa5728a6f76199a3da1750ed952e7efee17c1da