#!/bin/sh

if [ "$1" = "-" ]; then
  cat
else
  git log --pretty=format:'- [commit %h](https://github.com/PowerDNS/pdns/commit/%h): %s' "$@" |\
    sed -r 's!#([[:digit:]]+)![ticket #\1](https://github.com/PowerDNS/pdns/issues/\1)!g;'
fi
