#!/bin/sh
CC="ccache gcc" CXX="ccache g++" ./configure \
		--with-modules="mysql gmysql gpgsql gsqlite pipe pdns geo" \
		--with-pgsql-lib=/opt/postgresql/lib/ \
		--with-pgsql-includes=/opt/postgresql/include/ \
	--with-dynmodules="" \
	--enable-static-binaries --enable-recursor \
	--prefix=/usr \
	--sysconfdir=/etc/powerdns \
&& make clean && make && \
fakeroot /bin/sh -c "rm -rf /tmp/pdns ; DESTDIR=/tmp/pdns make install-strip" &&
fakeroot mkdir -p /tmp/pdns/etc/init.d &&
fakeroot cp pdns/pdns /tmp/pdns/etc/init.d/pdns &&
fakeroot mkdir -p /tmp/pdns/etc/powerdns &&
fakeroot mv /tmp/pdns/etc/powerdns/pdns.conf-dist /tmp/pdns/etc/powerdns/pdns.conf &&
fakeroot rpm -bb pdns.spec

