#!/bin/bash 
VERSION=$1
[ -z "$VERSION" ] && exit

ssed -r "s/Version: (.*)/Version: \\1.$VERSION/" -i *.spec
ssed -r "s/AM_INIT_AUTOMAKE\\(pdns, (.*)\\)/AM_INIT_AUTOMAKE\(pdns, \\1.$VERSION\)/" -i configure.ac
ssed -r "s/^pdns \\(([^-]*(-rc[0-9])*)-[0-9]*\\)/pdns \\(\\1.$VERSION-1\\)/" -i debian-pdns/changelog

