#!/bin/sh

set -x
export PDNS=/usr/sbin/pdns_server
export PDNS2=$PDNS
export SDIG=/usr/bin/sdig
export NSEC3DIG=/usr/bin/nsec3dig
export SAXFR=/usr/bin/saxfr
export ZONE2SQL=/usr/bin/zone2sql
export PDNSSEC=/usr/bin/pdnssec
export PDNSCONTROL=/usr/bin/pdns_control

MODULES=""

for dir in /usr/lib/x86_64-linux-gnu/pdns /usr/lib64/pdns; do
  if [ -d $dir ]; then
    MODULES=$dir
    break
  fi
done
[ -z $MODULES ] && echo "No module directory found" >&2 && exit 1

# Symlink the modules on the system
cd regression-tests/modules
for backend in *.so; do
  ln -sf $MODULES/$backend $backend
done

cd ..

export geoipregion=oc geoipregionip=1.2.3.4
./timestamp ./start-test-stop 5300 bind-both
./timestamp ./start-test-stop 5300 bind-dnssec-both
./timestamp ./start-test-stop 5300 bind-dnssec-pkcs11
./timestamp ./start-test-stop 5300 bind-dnssec-nsec3-both
./timestamp ./start-test-stop 5300 bind-dnssec-nsec3-optout-both
./timestamp ./start-test-stop 5300 bind-dnssec-nsec3-narrow
./timestamp ./start-test-stop 5300 bind-hybrid-nsec3
./timestamp ./start-test-stop 5300 geoipbackend
./timestamp ./start-test-stop 5300 geoipbackend-nsec3-narrow
./timestamp ./start-test-stop 5300 gmysql-nodnssec-both
./timestamp ./start-test-stop 5300 gmysql-both
./timestamp ./start-test-stop 5300 gmysql-nsec3-both
./timestamp ./start-test-stop 5300 gmysql-nsec3-optout-both
./timestamp ./start-test-stop 5300 gmysql-nsec3-narrow
./timestamp ./start-test-stop 5300 gpgsql-nodnssec-both
./timestamp ./start-test-stop 5300 gpgsql-both
./timestamp ./start-test-stop 5300 gpgsql-nsec3-both
./timestamp ./start-test-stop 5300 gpgsql-nsec3-optout-both
./timestamp ./start-test-stop 5300 gpgsql-nsec3-narrow
./timestamp ./start-test-stop 5300 gsqlite3-nodnssec-both
./timestamp ./start-test-stop 5300 gsqlite3-both
./timestamp ./start-test-stop 5300 gsqlite3-nsec3-both
./timestamp ./start-test-stop 5300 gsqlite3-nsec3-optout-both
./timestamp ./start-test-stop 5300 gsqlite3-nsec3-narrow
#DNSName - ./timestamp ./start-test-stop 5300 lmdb-nodnssec
./timestamp ./start-test-stop 5300 mydns
./timestamp ./start-test-stop 5300 opendbx-sqlite3
./timestamp timeout 120s ./start-test-stop 5300 remotebackend-pipe
./timestamp timeout 120s ./start-test-stop 5300 remotebackend-pipe-dnssec
./timestamp timeout 120s ./start-test-stop 5300 remotebackend-unix
./timestamp timeout 120s ./start-test-stop 5300 remotebackend-unix-dnssec
./timestamp timeout 120s ./start-test-stop 5300 remotebackend-http
./timestamp timeout 120s ./start-test-stop 5300 remotebackend-http-dnssec
./timestamp timeout 120s ./start-test-stop 5300 remotebackend-zeromq
./timestamp timeout 120s ./start-test-stop 5300 remotebackend-zeromq-dnssec
./timestamp ./start-test-stop 5300 tinydns

cd ../regression-tests.nobackend/

# The package builds define other dirs, so the distconf test fails, so skip it
touch pdnsconfdist/skip

./runtests
test ! -s ./failed_tests
