#!/bin/sh

export PDNSRECURSOR=/usr/sbin/pdns_recursor
export SDIG=/usr/bin/sdig
export NSEC3DIG=/usr/bin/nsec3dig
export SAXFR=/usr/bin/saxfr

if [ "$0" != "./build-scripts/test-recursor" ]; then
  echo "Please run me from the root checkout dir"
  exit 1
fi

set -x

cd regression-tests.recursor
cp vars.sample vars
sed -i 's!PREFIX=.*!PREFIX=127.0.0!' vars

EXIT=0

./config.sh
./start.sh
sleep 3
svstat configs/*
./runtests || EXIT=1
./stop.sh
sleep 3
./clean.sh

exit $EXIT
