#!/bin/sh
ldns-verify-zone -h | head -n 1
for zone in $(grep zone named.conf  | cut -f2 -d\" | grep -v '^example.com$')
do
	TFILE=$(mktemp)
	dig axfr $zone @$nameserver -p $port > $TFILE
	echo --- ldns-verify-zone $zone
	ldns-verify-zone -V2 $TFILE 2>&1
	echo RETVAL: $?
	rm -f $TFILE
done
