---
name: Build packages for tags

on:
  push:
    tags:
    - 'auth-*'
    - 'dnsdist-*'
    - 'rec-*'

permissions:
  actions: read
  id-token: write
  contents: write

jobs:
  call-build-packages-auth:
    uses: PowerDNS/pdns/.github/workflows/build-packages.yml@master
    if: startsWith(github.ref_name, 'auth')
    with:
      is_release: 'YES'
      product: 'authoritative'
      ref: ${{ github.ref_name }}
    secrets:
      DOWNLOADS_AUTOBUILT_SECRET: ${{ secrets.DOWNLOADS_AUTOBUILT_SECRET }}
      DOWNLOADS_AUTOBUILT_RSYNCTARGET: ${{ secrets.DOWNLOADS_AUTOBUILT_RSYNCTARGET }}
      DOWNLOADS_AUTOBUILT_HOSTKEY: ${{ secrets.DOWNLOADS_AUTOBUILT_HOSTKEY }}

  call-build-packages-dnsdist:
    uses: PowerDNS/pdns/.github/workflows/build-packages.yml@master
    if: startsWith(github.ref_name, 'dnsdist')
    with:
      is_release: 'YES'
      product: 'dnsdist'
      ref: ${{ github.ref_name }}
    secrets:
      DOWNLOADS_AUTOBUILT_SECRET: ${{ secrets.DOWNLOADS_AUTOBUILT_SECRET }}
      DOWNLOADS_AUTOBUILT_RSYNCTARGET: ${{ secrets.DOWNLOADS_AUTOBUILT_RSYNCTARGET }}
      DOWNLOADS_AUTOBUILT_HOSTKEY: ${{ secrets.DOWNLOADS_AUTOBUILT_HOSTKEY }}

  call-build-packages-rec:
    uses: PowerDNS/pdns/.github/workflows/build-packages.yml@master
    if: startsWith(github.ref_name, 'rec')
    with:
      is_release: 'YES'
      product: 'recursor'
      ref: ${{ github.ref_name }}
    secrets:
      DOWNLOADS_AUTOBUILT_SECRET: ${{ secrets.DOWNLOADS_AUTOBUILT_SECRET }}
      DOWNLOADS_AUTOBUILT_RSYNCTARGET: ${{ secrets.DOWNLOADS_AUTOBUILT_RSYNCTARGET }}
      DOWNLOADS_AUTOBUILT_HOSTKEY: ${{ secrets.DOWNLOADS_AUTOBUILT_HOSTKEY }}
