---
name: Build packages for tags

on:
  push:
    tags:
    - 'auth-*'
    - 'dnsdist-*'
    - 'rec-*'

# Please be aware that this version of the workflow is NOT the one called
# when someone pushes a tag on a release branch (rel/**)! The version
# used is the one present in the tag, which in turns should call the
# version present in the master branch of the reusable workflow defined
# in .github/workflows/build-packages.yml
# This means that any change to this file will very likely need to be
# backported to all release branches!!

permissions:
  actions: read
  id-token: write
  contents: write

jobs:
  call-build-packages-auth:
    uses: PowerDNS/pdns/.github/workflows/build-packages.yml@master
    if: startsWith(github.ref_name, 'auth')
    with:
      is_release: 'YES'
      product: 'authoritative'
      ref: ${{ github.ref_name }}
    secrets:
      DOWNLOADS_AUTOBUILT_SECRET: ${{ secrets.DOWNLOADS_AUTOBUILT_SECRET }}
      DOWNLOADS_AUTOBUILT_RSYNCTARGET: ${{ secrets.DOWNLOADS_AUTOBUILT_RSYNCTARGET }}
      DOWNLOADS_AUTOBUILT_HOSTKEY: ${{ secrets.DOWNLOADS_AUTOBUILT_HOSTKEY }}
      PULP_FILE_REPO_NAME: ${{ secrets.PULP_FILE_REPO_NAME }}
      PULP_URL: ${{ secrets.PULP_URL }}
      PULP_CONTENT_URL: ${{ secrets.PULP_CONTENT_URL }}
      PULP_CI_USERNAME: ${{ secrets.PULP_CI_USERNAME }}
      PULP_CI_PASSWORD: ${{ secrets.PULP_CI_PASSWORD }}
      PULP_PDNS_GPG_PUBKEY_MASTER: ${{ secrets.PULP_PDNS_GPG_PUBKEY_MASTER }}
      PULP_PDNS_GPG_PUBKEY: ${{ secrets.PULP_PDNS_GPG_PUBKEY }}

  call-build-packages-dnsdist:
    uses: PowerDNS/pdns/.github/workflows/build-packages.yml@master
    if: startsWith(github.ref_name, 'dnsdist')
    with:
      is_release: 'YES'
      product: 'dnsdist'
      ref: ${{ github.ref_name }}
    secrets:
      DOWNLOADS_AUTOBUILT_SECRET: ${{ secrets.DOWNLOADS_AUTOBUILT_SECRET }}
      DOWNLOADS_AUTOBUILT_RSYNCTARGET: ${{ secrets.DOWNLOADS_AUTOBUILT_RSYNCTARGET }}
      DOWNLOADS_AUTOBUILT_HOSTKEY: ${{ secrets.DOWNLOADS_AUTOBUILT_HOSTKEY }}
      PULP_FILE_REPO_NAME: ${{ secrets.PULP_FILE_REPO_NAME }}
      PULP_URL: ${{ secrets.PULP_URL }}
      PULP_CONTENT_URL: ${{ secrets.PULP_CONTENT_URL }}
      PULP_CI_USERNAME: ${{ secrets.PULP_CI_USERNAME }}
      PULP_CI_PASSWORD: ${{ secrets.PULP_CI_PASSWORD }}
      PULP_PDNS_GPG_PUBKEY_MASTER: ${{ secrets.PULP_PDNS_GPG_PUBKEY_MASTER }}
      PULP_PDNS_GPG_PUBKEY: ${{ secrets.PULP_PDNS_GPG_PUBKEY }}

  call-build-packages-rec:
    uses: PowerDNS/pdns/.github/workflows/build-packages.yml@master
    if: startsWith(github.ref_name, 'rec')
    with:
      is_release: 'YES'
      product: 'recursor'
      ref: ${{ github.ref_name }}
    secrets:
      DOWNLOADS_AUTOBUILT_SECRET: ${{ secrets.DOWNLOADS_AUTOBUILT_SECRET }}
      DOWNLOADS_AUTOBUILT_RSYNCTARGET: ${{ secrets.DOWNLOADS_AUTOBUILT_RSYNCTARGET }}
      DOWNLOADS_AUTOBUILT_HOSTKEY: ${{ secrets.DOWNLOADS_AUTOBUILT_HOSTKEY }}
      PULP_FILE_REPO_NAME: ${{ secrets.PULP_FILE_REPO_NAME }}
      PULP_URL: ${{ secrets.PULP_URL }}
      PULP_CONTENT_URL: ${{ secrets.PULP_CONTENT_URL }}
      PULP_CI_USERNAME: ${{ secrets.PULP_CI_USERNAME }}
      PULP_CI_PASSWORD: ${{ secrets.PULP_CI_PASSWORD }}
      PULP_PDNS_GPG_PUBKEY_MASTER: ${{ secrets.PULP_PDNS_GPG_PUBKEY_MASTER }}
      PULP_PDNS_GPG_PUBKEY: ${{ secrets.PULP_PDNS_GPG_PUBKEY }}
