name: Test Developer Certificate of Origin

on:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: KineticCafe/actions-dco@1da04282bbf757dab7d92a5c8535dbfb8113da5c # 3.1.0
        with:
          exempt-authors: |
            @powerdns.com
            @open-xchange.com
