name: Test Developer Certificate of Origin

on:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: KineticCafe/actions-dco@f7fe2fdfb5808e2528042be3919b67079100b96b # 3.0.0
        with:
          exempt-authors: |
            @powerdns.com
            @open-xchange.com
